services:
  db:
    container_name: postgres-db
    image: postgres:latest
    environment:
      POSTGRES_USER: mrseams
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5332:5432"
    restart: unless-stopped